//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 01:52:00 PM MSK 
//


package com.javafordev.lesson9.task1.model.beer_shop.beer;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Beer" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "beer"
})
@XmlRootElement(name = "BeerOrder")
public class BeerOrder {

    @XmlElement(name = "Beer")
    protected List<Beer> beer;

    /**
     * Gets the value of the beer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Beer> getBeer() {
        if (beer == null) {
            beer = new ArrayList<>();
        }
        return this.beer;
    }

    public BeerOrder(List<Beer> beer) {
        this.beer = beer;
    }

    public BeerOrder() {
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        BeerOrder beerOrder = (BeerOrder) o;

        return beer != null ? beer.equals(beerOrder.beer) : beerOrder.beer == null;
    }

    @Override
    public int hashCode() {
        return beer != null ? beer.hashCode() : 0;
    }

    @Override
    public String toString() {
        return "BeerOrder{" +
                "beer=" + beer +
                '}';
    }
}
