//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 01:52:00 PM MSK 
//


package com.javafordev.lesson9.task1.model.beer_shop.beer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for Char complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Char">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="content" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *               &lt;minInclusive value="1.6"/>
 *               &lt;maxInclusive value="9.9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="transparency">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\d{1,2}%"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="filtered" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="nutrition" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="bottling" type="{http://www.beer-shop/beer}Bottling"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Char", propOrder = {

})
public class Char {

    @XmlElement()
    protected Double content;
    @XmlElement(required = true)
    protected String transparency;
    protected boolean filtered;
    @XmlElement(required = true)
    protected int nutrition;
    @XmlElement(required = true)
    protected Bottling bottling;

    public Char(Double content, String transparency, boolean filtered, int nutrition, Bottling bottling) {
        this.content = content;
        this.transparency = transparency;
        this.filtered = filtered;
        this.nutrition = nutrition;
        this.bottling = bottling;
    }

    public Char() {
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setContent(Double value) {
        this.content = value;
    }

    /**
     * Gets the value of the transparency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransparency() {
        return transparency;
    }

    /**
     * Sets the value of the transparency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransparency(String value) {
        this.transparency = value;
    }

    /**
     * Gets the value of the filtered property.
     * 
     */
    public boolean isFiltered() {
        return filtered;
    }

    /**
     * Sets the value of the filtered property.
     * 
     */
    public void setFiltered(boolean value) {
        this.filtered = value;
    }

    /**
     * Gets the value of the nutrition property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getNutrition() {
        return nutrition;
    }

    /**
     * Sets the value of the nutrition property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNutrition(int value) {
        this.nutrition = value;
    }

    /**
     * Gets the value of the bottling property.
     * 
     * @return
     *     possible object is
     *     {@link Bottling }
     *     
     */
    public Bottling getBottling() {
        return bottling;
    }

    /**
     * Sets the value of the bottling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bottling }
     *     
     */
    public void setBottling(Bottling value) {
        this.bottling = value;
    }

    @Override
    public String toString() {
        return "Char{" +
                "content=" + content +
                ", transparency='" + transparency + '\'' +
                ", filtered=" + filtered +
                ", nutrition=" + nutrition +
                ", bottling=" + bottling +
                '}';
    }
}
